[package]
name = "gstest1"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "an useful function"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
